# General Settings
log_file: "logfile_multi_system.log" # Log file name
num_workers: 0                       # Number of workers for DataLoader
force_cpu: false                     # Set to true to force CPU usage
cuda_device: 0                       # GPU index if CUDA is available and force_cpu is false

# --- DATA INPUT CONFIGURATION (MODIFIED FOR MULTI-SYSTEM) ---
# Each entry in the 'systems' list represents one protein to be trained on.
data:
  systems:

    # --- System 1 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_d2_inv_start/run6/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_d2_inv_start/run6/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_d2_inv_start/run6/condensed.json"

    # --- System 2 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_d1/run1/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_d1/run1/residues_data_0.5.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_d1/run1/condensed.json"

    # --- System 3 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_A2AR/run1/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_A2AR/run1/residues_data_0.1.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_A2AR/run1/condensed.json"

    # --- System 4 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_beta1/run1/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_beta1/run1/residues_data_0.5.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_beta1/run1/condensed.json"

    # --- System 5 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_M1/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_M1/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_M1/condensed.json"

    # --- System 6 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_H1/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_H1/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_H1/condensed.json"

    # --- System 7 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_d3/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_d3/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_d3/condensed.json"

    # --- System 8 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_beta2/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_beta2/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_beta2/condensed.json"

    # --- System 9 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_h5t2a/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_h5t2a/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_h5t2a/condensed.json"

    # --- System 10 ---
    - pdb_path: "/scratch/asengar/long_sim/apo_5ht1b/heavy_chain.pdb"
      json_path: "/scratch/asengar/long_sim/apo_5ht1b/residues_data.json"
      torsion_info_path: "/scratch/asengar/long_sim/apo_5ht1b/condensed.json"


# Graph Construction Settings
graph:
  knn_value: 4                       # K for k-NN graph construction

# --- GLOBAL MODEL & TRAINING SETTINGS ---
# These settings apply to the single, shared models trained on all systems.
hno_encoder:
  hidden_dim: 16
  cheb_order: 4
  num_epochs: 5
  learning_rate: 0.0001
  batch_size: 16
  save_interval: 50

decoder2:
  num_epochs: 10
  learning_rate: 0.0003
  batch_size: 16
  base_loss_weight: 1.0
  save_interval: 500
  use_z_ref_ensemble: false

decoder2_settings:
  conditioner_mode: "z_ref"          # Must be 'z_ref' for the multi-system code
  mlp_hidden_dim: 16
  num_hidden_layers: 12
  # NOTE: pooling_type, output_height/width are no longer used by the new decoder
  pooling_type: "blind"
  output_height: 50
  output_width: 2

# Dihedral Loss Configuration (Global Weights)
dihedral_loss:
  # This is a global switch. Set to true to attempt using dihedral loss.
  use_dihedral_loss: false
  # The specific torsion_info_path is now defined per-system above.
  lambda_divergence: 0.1
  lambda_torsion_mse: 1.0
  divergence_type: "JS"

# Data Augmentation Settings
data_augmentation:
  enabled: true
  ensemble_size: 50
  target_ca_rmsd: 1.0

# Structural Augmentation Settings
structural_augmentation:
  enabled: true
  variants_per_system: 10

# Execution Settings
execution_settings:
  limit_systems: 2
  max_frames_per_system: 500

# Output Directories Configuration
output_directories:
  checkpoint_dir: "checkpoints"
  structure_dir: "structures"
  latent_dir: "latent_reps"
