# General Settings
log_file: "logfile_multi_system.log" # Log file name
num_workers: 0                       # Number of workers for DataLoader
force_cpu: false                     # Set to true to force CPU usage
cuda_device: 0                       # GPU index if CUDA is available and force_cpu is false

# --- DATA INPUT CONFIGURATION (MODIFIED FOR MULTI-SYSTEM) ---
# Each entry in the 'systems' list represents one protein to be trained on.
data:
  systems:
    # --- System 1 ---
    - pdb_path: "d1/heavy_chain.pdb"
      json_path: "d1/residues_data.json"
      torsion_info_path: "d1/condensed.json" # Torsion map for system 1

    # --- System 2 ---
    - pdb_path: "d2/heavy_chain.pdb"
      json_path: "d2/residues_data.json"
      torsion_info_path: "d2/condensed.json" # Torsion map for system 2

# Graph Construction Settings
graph:
  knn_value: 4                       # K for k-NN graph construction

# --- GLOBAL MODEL & TRAINING SETTINGS ---
# These settings apply to the single, shared models trained on all systems.
hno_encoder:
  hidden_dim: 8
  cheb_order: 4
  num_epochs: 10
  learning_rate: 0.0001
  batch_size: 16
  save_interval: 500

decoder2:
  num_epochs: 10
  learning_rate: 0.0003
  batch_size: 16
  base_loss_weight: 1.0
  save_interval: 500

decoder2_settings:
  conditioner_mode: "z_ref"          # Must be 'z_ref' for the multi-system code
  mlp_hidden_dim: 128
  num_hidden_layers: 12
  # NOTE: pooling_type, output_height/width are no longer used by the new decoder
  pooling_type: "blind"
  output_height: 50
  output_width: 2

# Dihedral Loss Configuration (Global Weights)
dihedral_loss:
  # This is a global switch. Set to true to attempt using dihedral loss.
  use_dihedral_loss: false
  # The specific torsion_info_path is now defined per-system above.
  lambda_divergence: 0.1
  lambda_torsion_mse: 1.0
  divergence_type: "JS"

# Output Directories Configuration
output_directories:
  checkpoint_dir: "checkpoints"
  structure_dir: "structures"
  latent_dir: "latent_reps"
